module.exports = [
  'apple','banana','guitar','pizza','castle','dragon','rocket','sunset','diamond','penguin',
  'volcano','rainbow','umbrella','butterfly','telescope','elephant','cactus','lighthouse','tornado',
  'submarine','snowflake','jellyfish','pyramid','compass','lantern','anchor','trophy','hourglass',
  'camera','hammer','crown','feather','candle','bridge','keyboard','robot','wizard','ninja',
  'pirate','astronaut','mermaid','unicorn','phoenix','vampire','werewolf','zombie','ghost',
  'detective','superhero','samurai','knight','archer','sorcerer','fireman','surgeon','chef',
  'basketball','football','tennis','volleyball','cricket','bowling','archery','swimming','cycling',
  'skateboarding','surfing','snowboarding','climbing','boxing','wrestling','fencing','sailing',
  'guitar','piano','violin','trumpet','drum','saxophone','flute','harp','accordion',
  'burger','sushi','tacos','pasta','ramen','curry','steak','salad','donut','waffle',
  'lion','tiger','bear','wolf','fox','eagle','shark','dolphin','octopus','crocodile',
  'spaceship','satellite','blackhole','comet','meteor','galaxy','nebula','supernova','quasar',
  'castle','dungeon','tower','fortress','temple','pyramid','colosseum','maze','cave','island',
  'storm','blizzard','avalanche','earthquake','tsunami','hurricane','eclipse','aurora','fog',
  'sword','shield','bow','axe','dagger','spear','crossbow','cannon','catapult',
  'clock','mirror','window','ladder','rope','key','lock','magnet','battery','circuit',
  'parachute','glider','helicopter','submarine','hovercraft','zeppelin','canoe','catamaran',
  'cookie','icecream','chocolate','lollipop','pretzel','popcorn','marshmallow','cupcake',
  'backpack','tent','campfire','flashlight','sleeping bag','canteen','map','whistle',
  'crab','lobster','seahorse','starfish','clam','seagull','pelican','walrus','seal','otter',
];
